import 'package:meta/meta.dart';

/// {@template openai_edit_model_choice}
/// This class is used to represent a choice generated by an OpenAI edit.
/// {@endtemplate}
@immutable
final class EditChoice {
  /// The text of the choice.
  final String text;

  /// The index of the choice.
  final int index;

  @override
  int get hashCode => text.hashCode ^ index.hashCode;

  /// {@macro openai_edit_model_choice}
  const EditChoice({
    required this.text,
    required this.index,
  });

  /// {@macro openai_edit_model_choice}
  /// This method is used to convert a [Map<String, dynamic>] object to a [EditChoice] object.
  factory EditChoice.fromMap(Map<String, dynamic> json) {
    return EditChoice(
      text: json['text'],
      index: json['index'],
    );
  }

  @override
  bool operator ==(covariant EditChoice other) {
    if (identical(this, other)) return true;

    return other.text == text && other.index == index;
  }

  @override
  String toString() => 'OpenAIEditModelChoice(text: $text, index: $index)';
}
