name: flutter_openai
description: Flutter SDK for OpenAI APIs. Originally forked from https://github.com/anasfik/openai
version: 1.0.0
homepage: https://github.com/Glitch9Inc/flutter_openai/
repository: https://github.com/Glitch9Inc/flutter_openai/
documentation: https://github.com/Glitch9Inc/flutter_openai/blob/main/README.md
issue_tracker: hhttps://github.com/Glitch9Inc/flutter_openai/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  meta: ^1.9.1
  collection: ^1.17.2
  fetch_client: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.9
  dart_code_metrics: ^4.19.2
  lints: ^3.0.0
  test: ^1.24.3
