name: flutter_openai
description: Flutter SDK for OpenAI APIs. Originally forked from https://github.com/anasfik/openai
version: 1.0.1
homepage: https://github.com/Glitch9Inc/flutter_openai/
repository: https://github.com/Glitch9Inc/flutter_openai/
documentation: https://github.com/Glitch9Inc/flutter_openai/blob/main/README.md
issue_tracker: hhttps://github.com/Glitch9Inc/flutter_openai/issues
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  meta: ^1.9.1
  collection: ^1.17.2
  fetch_client: ^1.0.2
  shared_preferences: ^2.0.8
  flutter_corelib:
    git:
      url: https://github.com/Glitch9Inc/flutter_corelib.git
      ref: master

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^4.0.0
  test: ^1.24.3
